version: "3.7"

x-deploy: &deploy
  deploy:
    replicas: 2
    update_config:
      parallelism: 1
      delay: 10s
      failure_action: rollback
      order: start-first
    restart_policy:
      condition: any
      delay: 5s
      max_attempts: 0

x-envs: &envs
  environment:
  - APP_ENV=dev
  - APP_SECRET=
  - JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
  - JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
  - JWT_PASSPHRASE=
  - JWT_TOKENTTL=900 # 15 Minutos
  - JWT_REFRESHTTL=7889400 # 3 Meses
  - REDIS_URL=redis://redis
  - DATABASE_URL=mysql://{{DATABASE_USER}}:{{DATABASE_PASSWORD}}@10.177.119.253:3357/{{DATABASE_NAME}}?serverVersion=5.7
  - SYMFONY_TOOLS_CORS='["https://{{FRONTEND_DOMAIN}}"]'
  - MAILER_URL=smtp://10.177.119.145:26
  - RESTORE_PASSWORD_SUBJECT="Recuperación de contraseña"
  - RESTORE_PASSWORD_FROM_NAME="From Name"
  - RESTORE_PASSWORD_FROM_EMAIL="example@example.com"
  - RESTORE_PASSWORD_INTERVAL=5
  - RESTORE_PASSWORD_URL="https://{{FRONTEND_DOMAIN}}}/#/restore/"
  - STORAGE_FILES_TMP="%kernel.project_dir%/storage-tmp/"
  - STORAGE_FILES="%kernel.project_dir%/storage/"
services:
  backend-php-fpm:
    image: {{GITLAB_REGISTRY}}/php-fpm:stage
    <<: *deploy
    <<: *envs
    volumes:
    - /opt/docker-apps/.mounts/{{STACK_NAME}}/jwt:/opt/symfony/config/jwt
    - /opt/docker-apps/.mounts/{{STACK_NAME}}/storage:/opt/symfony/storage
    - /opt/docker-apps/.mounts/{{STACK_NAME}}/storage-tmp:/opt/symfony/storage-tmp
    networks:
      {{STACK_NAME}}:
        aliases:
          - php-fpm

  backend-nginx:
    image: {{GITLAB_REGISTRY}}/nginx:stage
    <<: *deploy
    networks:
      {{STACK_NAME}}:
    ports:
    - 30034:80

  frontend:
    image: {{GITLAB_REGISTRY}}/web/stage:stage
    <<: *deploy
    networks:
      {{STACK_NAME}}:
    ports:
    - 30033:80

  redis:
    image: hub.irontec.com/internet/dockerfiles/redis/5.0.7:0.2.1

networks:
  {{STACK_NAME}}:
