version: "3.4"
services:
  nginx:
    hostname:       ${NAME}-nginx
    container_name: ${NAME}-nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - 'NGINX_V=${NGINX_V}'
    volumes:
      - ./symfony:/opt/symfony
    links:
      - php-fpm
    dns:
      - 10.10.0.4
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${NGINX_PORT}:443"
    networks:
      - ${NETWORK}

  php-fpm:
    hostname:       ${NAME}-fpm
    container_name: ${NAME}-fpm
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - 'NAME=${NAME}'
        - 'XDEBUG=${XDEBUG}'
    volumes:
        - ./symfony:/opt/symfony
        - /etc/hosts:/etc/hosts
    links:
      - mysql
      - redis
    dns:
      - 10.10.0.4
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - ${NETWORK}
#    environment:
#      - DOCKER_HEALTHCHECK=/opt/symfony/vendor/bin/simple-phpunit tests/HealthCheckControllerTest.php
#    healthcheck:
#      test: ["CMD", "/opt/symfony/vendor/bin/simple-phpunit", "tests/HealthCheckControllerTest.php"]
#      interval: '5m30s'
#      timeout: '30s'
#      retries: 2

  mysql:
    hostname:       ${NAME}-mysql
    container_name: ${NAME}-mysql
#https://dev.mysql.com/doc/refman/8.0/en/binary-log.html
    command: --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password --skip-log-bin --disable-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
      - ./docker/mysql/storage:/var/lib/mysql
    networks:
      - ${NETWORK}

  redis:
    hostname:       ${NAME}-redis
    container_name: ${NAME}-redis
    build:
      context: ./
      dockerfile: ./docker/redis/Dockerfile
    networks:
      - ${NETWORK}

networks:
  irondev:
    external: true
