build:
  tags:
    - docker
    - runners
  stage: build
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
    - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH/php-fpm:$CI_COMMIT_TAG -t $REGISTRY_HOST/$CI_PROJECT_PATH/php-fpm:latest -f ./docker/php-fpm/Dockerfile .
    - docker build --build-arg PHP_IMAGE=$REGISTRY_HOST/$CI_PROJECT_PATH/php-fpm:$CI_COMMIT_TAG -t $REGISTRY_HOST/$CI_PROJECT_PATH/nginx:$CI_COMMIT_TAG -t $REGISTRY_HOST/$CI_PROJECT_PATH/nginx:latest -f docker/nginx/Dockerfile .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/nginx:$CI_COMMIT_TAG
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/nginx:latest
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/php-fpm:$CI_COMMIT_TAG
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH/php-fpm:latest

